quarkus:
  http:
    port: 80
  datasource:
    username: root
    password: 1433223abc.
    jdbc:
      url: jdbc:mysql://117.50.174.154:60002/dinin
      driver: com.mysql.cj.jdbc.Driver
  smallrye-openapi:
    enable: true
  swagger-ui:
    enable: true